[package]
name = "platformer"
version = "0.1.0"
authors = ["Evan Almloff"]

[dependencies]
iron_oxide = { path = "../../lib" }

# building is optimized, but slow
[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
